// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VisitXpress.Repositories.Data;

#nullable disable

namespace VisitXpress.Repositories.Migrations
{
    [DbContext(typeof(VisitXpressDbContext))]
    [Migration("20251129163718_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("VisitXpress.Repositories.Entities.AccessArea", b =>
                {
                    b.Property<int>("AccessAreaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AccessAreaId"));

                    b.Property<string>("AreaName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AccessAreaId");

                    b.ToTable("AccessAreas");
                });

            modelBuilder.Entity("VisitXpress.Repositories.Entities.Attachment", b =>
                {
                    b.Property<int>("AttachmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AttachmentId"));

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("VisitorId")
                        .HasColumnType("int");

                    b.HasKey("AttachmentId");

                    b.HasIndex("VisitorId");

                    b.ToTable("Attachments");
                });

            modelBuilder.Entity("VisitXpress.Repositories.Entities.Badge", b =>
                {
                    b.Property<int>("BadgeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BadgeId"));

                    b.Property<string>("QrCodeValue")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("VisitId")
                        .HasColumnType("int");

                    b.HasKey("BadgeId");

                    b.HasIndex("VisitId")
                        .IsUnique();

                    b.ToTable("Badges");
                });

            modelBuilder.Entity("VisitXpress.Repositories.Entities.Employee", b =>
                {
                    b.Property<int>("EmployeeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EmployeeId"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EmployeeId");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("VisitXpress.Repositories.Entities.Visit", b =>
                {
                    b.Property<int>("VisitId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VisitId"));

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("VisitEnd")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("VisitStart")
                        .HasColumnType("datetime2");

                    b.Property<int>("VisitorId")
                        .HasColumnType("int");

                    b.HasKey("VisitId");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("VisitorId");

                    b.ToTable("Visits");
                });

            modelBuilder.Entity("VisitXpress.Repositories.Entities.VisitAccess", b =>
                {
                    b.Property<int>("VisitId")
                        .HasColumnType("int");

                    b.Property<int>("AccessAreaId")
                        .HasColumnType("int");

                    b.HasKey("VisitId", "AccessAreaId");

                    b.HasIndex("AccessAreaId");

                    b.ToTable("VisitAccesses");
                });

            modelBuilder.Entity("VisitXpress.Repositories.Entities.Visitor", b =>
                {
                    b.Property<int>("VisitorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VisitorId"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("VisitorId");

                    b.ToTable("Visitors");
                });

            modelBuilder.Entity("VisitXpress.Repositories.Entities.Attachment", b =>
                {
                    b.HasOne("VisitXpress.Repositories.Entities.Visitor", "Visitor")
                        .WithMany("Attachments")
                        .HasForeignKey("VisitorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Visitor");
                });

            modelBuilder.Entity("VisitXpress.Repositories.Entities.Badge", b =>
                {
                    b.HasOne("VisitXpress.Repositories.Entities.Visit", "Visit")
                        .WithOne("Badge")
                        .HasForeignKey("VisitXpress.Repositories.Entities.Badge", "VisitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Visit");
                });

            modelBuilder.Entity("VisitXpress.Repositories.Entities.Visit", b =>
                {
                    b.HasOne("VisitXpress.Repositories.Entities.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VisitXpress.Repositories.Entities.Visitor", "Visitor")
                        .WithMany("Visits")
                        .HasForeignKey("VisitorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("Visitor");
                });

            modelBuilder.Entity("VisitXpress.Repositories.Entities.VisitAccess", b =>
                {
                    b.HasOne("VisitXpress.Repositories.Entities.AccessArea", "AccessArea")
                        .WithMany("Visits")
                        .HasForeignKey("AccessAreaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VisitXpress.Repositories.Entities.Visit", "Visit")
                        .WithMany("VisitAccessAreas")
                        .HasForeignKey("VisitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AccessArea");

                    b.Navigation("Visit");
                });

            modelBuilder.Entity("VisitXpress.Repositories.Entities.AccessArea", b =>
                {
                    b.Navigation("Visits");
                });

            modelBuilder.Entity("VisitXpress.Repositories.Entities.Visit", b =>
                {
                    b.Navigation("Badge");

                    b.Navigation("VisitAccessAreas");
                });

            modelBuilder.Entity("VisitXpress.Repositories.Entities.Visitor", b =>
                {
                    b.Navigation("Attachments");

                    b.Navigation("Visits");
                });
#pragma warning restore 612, 618
        }
    }
}
